### ISSUE TITLE
[APP] - Sliders and Submit Button for Numerical Label

### ISSUE THREAD

**Issue by sshekdar-VMware** [vmware/data-annotator-for-machine-learning#102]
Numerical annotation is completed by entering a number within the given range in the text-box and pressing enter. To make this interface more congruent and intuitive it would be appropriate to add a submit button (already present for categorical annotation) and a slider with a text box to indicate the numerical annotation.

Numerical Annotation:
![image](https://user-images.githubusercontent.com/87147229/129285411-ef3b0f51-d6ca-4e75-8a7c-1d88839826f7.png)

Categorical Annotation:
![image](https://user-images.githubusercontent.com/87147229/129285433-5468680c-1a61-4801-8900-2790c88693f6.png)

Slider Example:
![image](https://user-images.githubusercontent.com/87147229/129285529-cd5af9d9-678f-40a6-9ba4-2a2b86e22132.png)

```html
<div class="slidecontainer">
  <input type="range" min="1" max="100" value="50" class="slider" id="myRange">
</div>
```

[w3 Schools Sliders in HTML](https://www.w3schools.com/howto/howto_js_rangeslider.asp)

**Comment by yangrong16** [comment]
- text input can input any number like integer and decimal.
- the slider increase by single step, it has default step is one.
- in my opinion, text input is more flexible than slider. @sshekdar-VMware
