### ISSUE TITLE
Support authentication using LDAP

### ISSUE THREAD

**Issue by lijulia** [vmware/data-annotator-for-machine-learning#177]
DAML should support LDAP authentication in the config file so I can login to DAML using my LDAP account instead of creating another DAML account.

**Comment by Kai-Qiao** [comment]
@yangrong16 
when the user selects login directly with LDAP without the registry, should pass the parameters as below
```
{
    "email":"xxxxxxx@xxxxxxx.com", 
    "password":"xxxxxxx",
    "ldap":true
}
```
response as the normal:
```
{
    "token": {
        "access_token": "xxxxxxx",
        "access_type": "Bearer",
        "expires_in": 1800,
        "expires_time": xxxxxxx
    },
    "email": "xxxxxxx",
    "fullName": "xxxxxxx",
    "role": "xxxxxxx"
}
```
