### ISSUE TITLE
Add ability to UI to select different spacy models (for different languages and model sizes)

### ISSUE THREAD

**Issue by gremur** [vmware/data-annotator-for-machine-learning#233]
### Is your feature request related to a problem? Please describe.

There is no easy way to change Spacy model name used in tool. Now Spacy model name 'en_core_web_md' is hard-coded in the '/active-learning-service/src/al/et_vectors.py'. Changes of Spacy model name in the file will be overwritten when the tool version is updated.

### Describe the solution you'd like

It would be useful to be able to change the Spacy models used in the user interface. Thank you.

**Comment by lijulia** [comment]
Hi @gremur Thanks for your suggestions!  The feature request here has been captured into our list and we’re going to take it into consideration as we develop more AL capabilities.

For now, we can make a quick fix to load the Spacy model using the config file. What are your thoughts?

**Comment by gremur** [comment]
Hello @lijulia. Thank you foe accepting the enhancement. Suggested quick fix with config file would be a good solution I believe.

**Comment by Kai-Qiao** [comment]
Hi @gremur , we have been supported this enhancement now,  when you build to start the application you can update the [active-learning-service/config/app_os.py](https://github.com/vmware/data-annotator-for-machine-learning/blob/master/active-learning-service/config/app_os.py#L23) file or you can pass the **SPACY_MODEL** in your system environment. you can reference [BUILD.md](https://github.com/vmware/data-annotator-for-machine-learning/blob/master/BUILD.md), if you are using docker version you can reference [RUN-WITH-DOCKER.md](https://github.com/vmware/data-annotator-for-machine-learning/blob/master/RUN-WITH-DOCKER.md)
