### ISSUE TITLE
"Invalid token" on http://localhost:3000/

### ISSUE THREAD

**Issue by bilykigor** [vmware/data-annotator-for-machine-learning#260]
### Describe the bug

Both started with docker or locally I get {"MSG":"Invalid token"}
from http://localhost:3000/

### Reproduction steps

```bash
Start service as described in docs
Open http://localhost:3000/ in browser
```

### Expected behavior

UI visible

**Comment by Kai-Qiao** [comment]
@bilykigor `http://localhost:3000/` is the annotation-service **API URL**, you should open `http://localhost:4200` in browser to use the application.

**Comment by Kai-Qiao** [comment]
we add a how to use statement for the users in the readme file.
@bilykigor is it ok to run the data-annotator-for-machine-learning (DAML) application on your pc, now?
if any problem please contact us thanks.
