### ISSUE TITLE
Cannot start app docker container

### ISSUE THREAD

**Issue by matteobarato** [vmware/data-annotator-for-machine-learning#290]
### Describe the bug

During the start up of vmware-daml-annotation-app the follow error is occurred:
"exec /docker-entrypoint.sh: no such file or directory"

### Reproduction steps

```bash
1.Downloading the repo
2.Run: sudo docker-compose -f docker-compose.yml up
```

### Expected behavior

Following the repo the site will be available on localhost:4200, but nothing is available

### Additional context

OS: Ubuntu 22.04 LTS

**Comment by matteobarato** [comment]
The same happened with docker-compose-host-db.yml

**Comment by lijulia** [comment]
Thanks for reporting the issue.  We will look into it asap.

**Comment by Kai-Qiao** [comment]
Hi @matteobarato 
you can update the latest code and remove the docker images using the below command, and then try again.
1. sync the latest code from Github. at DAML root folder run the below command to remove docker instances first.
```bash
docker compose -f docker-compose.yml down
```
2. remove older docker images 
```bash
docker rmi 1107899648/vmware-daml-annotation-app 1107899648/vmware-daml-active-learning-service 1107899648/vmware-daml-annotation-service
```
3. run DAML with docker again.
```bash
docker compose -f docker-compose.yml up
```
4. open localhost:4200 with your browser to access DAML application

if anything please doesn't hesitate to ping us again. thanks.

**Comment by lijulia** [comment]
Hi @matteobarato, does the new image solve your issue?

**Comment by lijulia** [comment]
Since this issue seems resolved, I will close this.  
@matteobarato if you are still experiencing this issue, let us know.
