### ISSUE TITLE
Update review assignment logic to display the most uncertain tickets first

### ISSUE THREAD

**Issue by lijulia** [vmware/data-annotator-for-machine-learning#308]
### Is your feature request related to a problem? Please describe.

For the cases of max_annotators > 1,  each item can be labelled by more than one person and each annotator may label the item differently.  As a project owner, I want to review the labeling quality, but there is no way that I can review the most uncertain items first.  The display order is either in Random or Sequential order right now.  As a result, I have to go through many items to find the ones that are in disagreement and relabel them.

### Describe the solution you'd like

In the review page, the review items should be displayed in the order of most uncertain items first.

As an example, the project has 3 labels: A, B, C and assigned to 3 people, the max_annotators=3.

Item 1: 
Person 1: label A
Person 2: label A
Person 3: label C

Item 2: 
Person 1: label A
Person 2: label A
Person 3: label A

Item 3:
Person 1: label A
Person 2: label B
Person 3: label C

When I go to the project review page, I should see item 3 first, then item 1, and last item 2.

**Comment by Kai-Qiao** [comment]
- The case is only suited for TEXT and TABULAR projects when the maxAnnotation>1. as for NER, IMAGE, LOG the maxAnnotation=1.
- For TEXT and TABULAR numerical and multiple-numerical label projects are not suited. as they are a special scope. 
- So only TEXT, TABULAR text label, multiple-text label, and hierarchical-taxonomy label are supported.
