### ISSUE TITLE
Support markdown formatting in the UI

### ISSUE THREAD

**Issue by lijulia** [vmware/data-annotator-for-machine-learning#54]
It would be useful to add markdown support in the UI and use a flag to turn the formatting on and off.

**Comment by mkbhanda** [comment]
@annajung might help to add a mockup/description of how you want things to lock with and without support.

**Comment by annajung** [comment]
A quick example would be, right now text displayed in the UI is similiar to [raw version](https://raw.githubusercontent.com/vmware/data-annotator-for-machine-learning/master/README.md) of the markdown file. 

With the flag enabled for markdown support, I like to see the [markdown](https://github.com/vmware/data-annotator-for-machine-learning/blob/master/README.md) version of the text in the UI where both HTML and markdown are supported as it is on Github.

Hope this clarifies the ask. thank you!
